name: Send daily morning weather + commute notification

on:
  workflow_dispatch:
  schedule:
    - cron: '18 7 * 6-8 1-5'
      timezone: 'America/New_York'

jobs:
  send_daily_notification:
    name: Send daily notification
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Send daily notification
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          HOME_LATITUDE: ${{ secrets.HOME_LATITUDE }}
          HOME_LONGITUDE: ${{ secrets.HOME_LONGITUDE }}
          MBTA_ROUTE_ID: ${{ secrets.MBTA_ROUTE_ID }}
          MBTA_STOP_ID: ${{ secrets.MBTA_STOP_ID }}
          MBTA_DIRECTION_ID: ${{ secrets.MBTA_DIRECTION_ID }}
        run: uv run main.py
